
name: Ops Pipelines - Azure AD
trigger:
- master

resources:
  repositories:
  - repository: ops-azure-ad
    type: github
    endpoint: hmcts
    name: hmcts/ops-azure-ad
    clean: true

steps:
- checkout: ops-azure-ad
  clean: true
  path: $(Build.SourcesDirectory)\ops-azure-ad


- task: AzurePowerShell@5
  inputs:
    azureSubscription: dcd-cnp-dev
    ScriptType: InLine
    inline: "ls -la"
    pwsh: true
    azurePowerShellVersion: latestVersion  

- task: AzurePowerShell@5
  inputs:
    azureSubscription: dcd-cnp-dev
    ScriptType: FilePath
    ScriptPath: $(Build.SourcesDirectory)\ops-azure-ad\aad.ps1
    pwsh: true
    azurePowerShellVersion: latestVersion