
name: Ops Pipelines - Azure AD
trigger:
- master

resources:
  repositories:
  - repository: ops-azure-ad
    type: github
    endpoint: hmcts
    name: hmcts/ops-azure-ad

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'dcd-cnp-dev'
    ScriptType: 'FilePath'
    ScriptPath: 'test'
    pwsh: true
