
name: Ops Pipelines - Azure AD
trigger:
- master

variables:
  userConfigPath: $(Build.SourcesDirectory)/vars/users
  groupConfigPath: $(Build.SourcesDirectory)/vars/groups

resources:
  repositories:
  - repository: ops-azure-ad
    type: github
    endpoint: hmcts
    name: hmcts/ops-azure-ad
    clean: true

steps:
- checkout: ops-azure-ad
  clean: true

- task: AzurePowerShell@5
  inputs:
    azureSubscription: dcd-cnp-dev
    ScriptType: FilePath
    ScriptPath: $(Build.SourcesDirectory)/aad.ps1
    azurePowerShellVersion: latestVersion
    scriptArguments:
      -UserConfigPath $(userConfigPath) 
      -GroupConfigPath $(groupConfigPath)
    azurePowerShellVersion: latestVersion